global:
  scrape_interval:     15s
  evaluation_interval: 30s
  external_labels:
    monitor: 'minio'

alerting:
  alertmanagers:
  - static_configs:
    - targets: 
      - 'alertmanager:9093'

rule_files:
- '/etc/prometheus/minio_rules.yml'

scrape_configs:
  - job_name: minio-job
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
    - targets: ['minio-nginx:9000']
